### ISSUE TITLE
Metrics-based classifier?

### ISSUE THREAD

**Issue by rchincha** [projectsveltos/classifier#371]
**Is your feature request related to a problem? Please describe.**

I am looking for a more dynamic classifier. 

**Describe the solution you'd like**

Given a project (not necessarily an addon), with a helm chart, I want to automatically apply this to a cluster which is "lightly" loaded - based on cpu or mem requests or any other metric. Conversely, remove an addon.

**Comment by gianlucam76** [comment]
Thank you @rchincha 

This is a great idea but though to implement in Sveltos. Cause Sveltos would have to be read metrics and there might be too combinations for that in different customer clusters. 

Have you considered creating/removing a Kubernetes resources based on metric? In your example, cluster is lightly loaded => create a ConfigMap In the managed cluster.
Cluster is highly loaded deleted the ConfigMap from the managed cluster.

Then use Sveltos event framework, to deploy the helm chart when the ConfigMap is created (which means your managed cluster s lightly loaded ) and remove the helm chart when the ConfigMap is deleted (which means your managed cluster is highly loaded)?

**Comment by kahirokunn** [comment]
Hi all,

**Follow-up to my new proposal in #375**

If *deployedResourceConstraint* is extended to reference resources that live in the **management cluster** (as suggested in #375), we can satisfy the “metrics-based classifier” request (#371) with nothing more than a **KeptnMetric**:

```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: Classifier
metadata:
  name: low-load
spec:
  classifierLabels:
  - key: load          # label applied to matching clusters
    value: low
  deployedResourceConstraint:
    resourceSelectors:
    - group: metrics.keptn.sh
      version: v1alpha1          # adjust to your Keptn version
      kind: KeptnMetric
      namespace: sveltos-metrics # KeptnMetric runs in the mgmt cluster
      name: keptnmetric-cpu-{{ .cluster }}
      evaluate: |
        function evaluate()
          local hs = { matching = false, message = "" }
          local v = tonumber(obj.status.value)
          if v and v < 0.5 then
            hs.matching = true          -- cluster is “low load”
          else
            hs.message = "CPU util " .. tostring(v)
          end
          return hs
        end
  # <--- new field proposed in #375
  sourceClusterScope: Local
```

**Why this works**

* `KeptnMetric.status.value` already carries the live metric.
* The Lua `evaluate` block checks the threshold directly—no extra controller required.
* When the metric crosses the line, the label is added or removed, and any ClusterProfile reacts automatically.

So, once #375’s enhancement lands, #371 can be closed with this declarative pattern.
