### ISSUE TITLE
Feature Request: Allow `deployedResourceConstraint` to evaluate resources in the management cluster

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/classifier#375]
**Is your feature request related to a problem? Please describe.**
In multi-cluster environments managed by Sveltos, we often want to deploy add-ons to *member* (workload) clusters **only if** a specific resource already exists in the **management (hub) cluster**.
Today, `spec.deployedResourceConstraints` can look only inside the candidate (workload) cluster itself, so we cannot express dependencies on management-cluster resources. As a result, platform teams must either duplicate configuration across clusters or rely on manual labeling—both error-prone and hard to automate.

**Describe the solution you'd like**
Extend `DeployedResourceConstraint` with an opt-in field (tentative name: `sourceClusterScope`) that tells the Classifier where to evaluate the resource:

```yaml
deployedResourceConstraints:
- group: ""
  version: v1
  kind: ConfigMap
  name: central-customer-license
  namespace: licensing
  sourceClusterScope: Local   # new enum: Current (default) | Local
```

* **Current** (default) → keeps today’s behavior (evaluate inside each candidate cluster).
* **Local** → evaluates the constraint against the mgmt cluster once; the result then drives labeling for every candidate cluster.

If the constraint matches, the Classifier labels the workload cluster as usual, allowing a `ClusterProfile` to select and install the desired resources.

**Describe alternatives you've considered**

* **Copy the resource into every workload cluster** via a separate controller or sync job – increases drift risk and network traffic.
* **Pre-label workload clusters manually** – does not adapt to changes, adds operational overhead.
* **External scripting** to call the k8s API and patch labels

**Additional context**

**Comment by gianlucam76** [comment]
##  Problem
  
The existing Classifier works by deploying sveltos-agent to every managed cluster. The agent evaluates the cluster's own resources — its workloads, its Kubernetes version, its installed CRDs. And reports back to the management cluster. The classifier controller then reads those reports and applies the declared labels to matching clusters.

This model is the right one when the classification signal lives inside the managed cluster. But sometimes it does not. A ConfigMap or Secret in the projectsveltos namespace may mark a cluster as belonging to a cost centre. An operator on the management cluster may maintain a registry of cluster tiers. A custom resource on the management cluster may record which clusters passed a compliance scan. For these cases, spinning up sveltos-agent just to read a management-cluster resource is wasteful and adds unnecessary latency.


## Solution  

**ManagementClusterClassifier** is a new cluster-scoped CRD. It watches resources on the management cluster itself and returns a list of clusters together with the labels to apply to each. The classifier controller processes the result and applies labels directly. No agent deployment, no round-trip to the managed cluster, no dependency on managed-cluster connectivity.

The spec has three fields:

- **matchResources**: one or more ResourceSelector entries describing which management-cluster resources to watch (GVK, namespace, label selector, optional per-resource CEL or Lua filter)
- **classificationLua**: a Lua function evaluate(resources) that receives all matched resources and returns a list of {namespace, name, kind} tables identifying which managed clusters to
  label
- **classifierLabels**: the {key, value} pairs to apply to every cluster the Lua function names

## How the classifier controller processes it

The reconcile loop runs entirely within the management cluster:

1. Lists all management-cluster resources matching matchResources, applying any per-resource CEL/Lua filter
2. Passes the full matched set to classificationLua, which returns the target cluster list
3. Applies classifierLabels to each named cluster via the Kubernetes API
4. Registers dynamic informer watches for every GVK in matchResources so any change to a watched resource immediately re-triggers the reconciler

Conflict detection reuses the existing keymanager. The first ManagementClusterClassifier to claim a label key on a cluster becomes its manager; others record the conflict in ManagementClusterClassifierReport.Status.UnManagedLabels. When the owning instance is deleted or its Lua function stops returning a cluster, the next in line takes over. The keymanager uses the prefix mgmt:<classifierName> internally so ManagementClusterClassifier names can never collide with regular Classifier names.

ManagementClusterClassifierReport is a namespace-scoped object (one per classifier + cluster pair, stored in the cluster's namespace). It records ManagedLabels and UnManagedLabels so the conflict state is visible in the API and so the keymanager can reconstruct its in-memory state after a restart.

### Concrete examples
1. Label a cluster based on a ConfigMap that names it
 
A platform team maintains a ConfigMap per cluster in the projectsveltos namespace carrying metadata that is not available inside the cluster itself (cost centre, business unit, environment tier).

```yaml
  # management cluster
  apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: projectsveltos
    name: cluster-meta-prod-eu1
    labels:
      sveltos.io/env: production
  data:
    clusterNamespace: capi-clusters
    clusterName: prod-eu1
  --- 
  apiVersion: lib.projectsveltos.io/v1beta1
  kind: ManagementClusterClassifier
  metadata: 
    name: tag-production-clusters
  spec:
    matchResources:
      - group: ""
        version: v1
        kind: ConfigMap
        namespace: projectsveltos
        selector:
          matchLabels:
            sveltos.io/env: production
    classificationLua: |
      function evaluate(resources)
        local result = {}
        for _, cm in ipairs(resources) do
          local ns   = cm.data.clusterNamespace
          local name = cm.data.clusterName
          if ns ~= nil and name ~= nil then
            table.insert(result, {namespace=ns, name=name, kind="Cluster"})
          end
        end
        return result
      end
    classifierLabels:
      - key: env
        value: production
      - key: cost-centre
        value: platform
```

 Every time a ConfigMap with label sveltos.io/env: production is created, updated, or deleted on the management cluster, the reconciler re-runs and the CAPI Cluster objects named in those ConfigMaps gain or lose the declared labels, with no agent round-trip.

2. Cross-resource logic: label a cluster only when both a licence and a quota approval exist

Sometimes the decision depends on multiple independent resources. classificationLua receives the union of everything matched by all matchResources entries and can implement arbitrary cross-resource logic.
  
```yaml
  apiVersion: lib.projectsveltos.io/v1beta1
  kind: ManagementClusterClassifier
  metadata: 
    name: fully-onboarded
  spec:
    matchResources:
      - group: ""
        version: v1   
        kind: ConfigMap
        namespace: projectsveltos
        selector:
          matchLabels:
            sveltos.io/doc-type: licence
      - group: ""
        version: v1   
        kind: ConfigMap
        namespace: projectsveltos
        selector:
          matchLabels:
            sveltos.io/doc-type: quota-approval
    classificationLua: |
      function evaluate(resources) 
        local licences = {}
        local quotas   = {}
        for _, cm in ipairs(resources) do
          local t = cm.metadata.labels["sveltos.io/doc-type"]
          local c = cm.data.clusterName
          if t == "licence"        then licences[c] = true end
          if t == "quota-approval" then quotas[c]   = true end
        end
        local result = {}
        for cluster, _ in pairs(licences) do
          if quotas[cluster] then
            table.insert(result, {namespace="capi-clusters", name=cluster, kind="Cluster"})
          end
        end 
        return result
      end
    classifierLabels:
      - key: onboarding-status
        value: complete
```  

A cluster receives onboarding-status=complete only when both a licence ConfigMap and a quota-approval ConfigMap exist for it on the management cluster. Deleting either document removes the label automatically.
